# -*- coding: utf-8 -*-
"""1(c).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ue8oaHSOGLcspSuWdF6gn398zpnkidB4
"""

#program 1
present_count=0
absent_count=0
total_students=50
print("Enter 'P' for present, 'A' fro absent, or 'END' to stop")
while(present_count+absent_count)<total_students:
      current_student=present_count+absent_count+1
      attendance=input(f"Student{current_student}:").strip().upper()
      if attendance=='END':
        print("Attendance tracking stoppe early")
        break
      elif attendance=='P':
        present_count+=1
      elif attendance=='A':
        absent_count+=1
      else:
        print("Invalid input!")
total_entered=present_count+absent_count
if total_entered>0:
      attendance_percentage=(present_count/total_entered)*100
else:
      attendance_percentage=0.0
print(f"Total present:{present_count}")
print(f"Total absent:{absent_count}")
print(f"Attendance percentage:{attendance_percentage:.2f}%")

#program2
score=0
total_questions=10
print("Enter 'C' for correct,'W' for wrong, or 'Quit' to exit")
for i in range (1,total_questions+1):
  answer=input(f"Question{i}Result:").strip().upper()
  if answer=='OCUIT':
    print("Quiz terminated by user.")
    break
  elif answer=='C':
    score+=5
  elif answer =='W':
    score==1
  else:
    print("Invalid input!Treated as unanswered")
if score>=40:
  grade='A'
elif score>=25:
  grade='B'
elif score>=10:
  grade='C'
else:
  grade='F'
print(f"Final score:{score} marks")
print(f"Grade:{grade}")