# -*- coding: utf-8 -*-
"""1(d) & 1(e).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wN2rK9xUbaQDoXIF2eL3Wsl2GgNH8zJ3
"""

#program 1
cart=["Laptop","Mouse","Keyboard"]
print(f"Step2:Initial cart:{cart}")
cart.append("Headphones")
print(f"Step3:After append:{cart}")

#program 2
emp_ids=(101,102,103,104,105)
print(f"Step2:Complete Employee ID tuple:{emp_ids}")
print(f"Step3:First employee ID:{emp_ids[0]}")
print(f"Step4:Last employee ID(negative index):{emp_ids[-1]}")

#program 3
students={"Arun","Priya","Rahul","Arun"}
print("Registered students:",students)
students.add("Kavin")
print("After adding Kavin:",students)
students.remove("Rahul")
print("After removing Rahul:",students)

#program 4
student={
    "No":101,
    "Name":"Kavya",
    "Class":12,
    "Age":17,
    "Marks":99,
}
print("Complete Record:",student)
print("Name:",student["Name"])
student["City"]="Erode"
print("After adding City:",student)

#program 5
first_name="Kavya"
last_name="Sri"
username=first_name[:3]+last_name[-3:]
print(f"Username:{username}")

#program 6
password="Python123"
is_strong=(len(password)>=8 and any(c.isupper() for c in password) and any(c.islower() for c in password) and any(c.isdigit() for c in password))
print("Strong password"if is_strong else"Weak password")

#program 7
email="student@gmail.com"
is_valid="@"in email and email.endswith(".com")and " " not in email
print("Valid Email"if is_valid else "Invalid Email")

#program 8
product_code="tv123lg"
formatted=f"{product_code[:2].upper()}-{product_code[2:5]}-{product_code[5:].upper()}"
print(f"Formatted:{formatted}")

#program 9
text="Python is easy. I love Python because Python is powerful."
cleaned_text=text.lower().replace("."," ").replace(","," ")
count=cleaned_text.split().count("python")
print(f"Python appers {count} times")

#program 10
msg="Machine Learnig"
decoded=" ".join(word[::-1] for word in msg.split())
print(f"Decoded:{decoded}")

#program 11
filename="assignment.pdf"
if filename.lower().endswith('.pdf'):
  print("PDF document")
elif filename.lower().endswith(('.jpg','.jpeg','.png')):
  print("Image file")
else:
  print("Unknown file type")

#program 12
message="I hate bad language"
banned_words=["bad","hate"]
for word in banned_words:
  message=message.replace(word,"***")
  print(message)

#program 13
passenger ="Priyanka"
mobile = '9876543210'
destination="New Delhi"
name_part=passenger[:2]
mobile_part=mobile[-4:]
words=destination.split()
destination_part=words[0][0]+words[1][0]
ticket_id=name_part+mobile_part+destination_part.upper()
print("Ticket ID:",ticket_id)

#program 14
feedback="The service was excellent and quick."
feedback=feedback.lower()
positive_words=["excellent","good","awesome"]
negative_words=["poor","bad","worst"]
if any(word in feedback for word in positive_words):
  print("Positive feedback")
elif any(word in feedback for word in negative_words):
  print("Negative feedback")
else:
  print("Netural feedback")